name: CI - Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read # Permissão para ler pacotes privados

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet Credentials and Restore
        run: |
          # Tentamos atualizar a fonte 'github' caso ela já exista no nuget.config
          dotnet nuget update source github --username dokatec --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --source "https://nuget.pkg.github.com/dokatec/index.json"
          dotnet restore
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore FCG-Users.sln

      - name: Build
        run: dotnet build FCG-Users.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test FCG-Users.sln --no-build --configuration Release
