name: CI - Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read # Permissão para ler pacotes privados

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Configurar NuGet para GitHub Packages
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source "https://nuget.pkg.github.com/dokatec/index.json" \
            --name github \
            --username dokatec \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore FCG-Users.sln

      - name: Build
        run: dotnet build FCG-Users.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test FCG-Users.sln --no-build --configuration Release
